[package]
name = "evm-precompile-identity"
version = "1.0.0-dev"
edition = "2021"
description = "Identity precompiles for EVM"

[dependencies]
rlp = { version = "0.5.1", default-features = false }
precompile-std = { version = "1.0.0-dev", path = "../precompile-std" }
sgx_tstd = { version="1.1.5", git = "https://github.com/apache/teaclave-sgx-sdk.git", branch="master" }

[patch."https://github.com/apache/teaclave-sgx-sdk.git"]
sgx_tstd = { version = "1.1.5", git = "https://github.com/haerdib/incubator-teaclave-sgx-sdk", branch = "master"}

[dev-dependencies]
hex = "0.4.3"
