name: Build Deb

on:
  push:
    branches: [feat/ci-deb]

jobs:
  build-deb:
    runs-on: ubuntu-latest
    env:
      SGX_MODE: HW
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the version
        id: get_version
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=VERSION::$(git rev-parse --short HEAD)"

      - name: Build .deb Package Image
        uses: docker/build-push-action@v4
        with:
          file: ./docker/node.Dockerfile
          context: .
          load: true
          tags: deb_build
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            SGX_MODE=HW
          target: build-deb
      - name: Run .deb Package Image
        run: |
          docker run -e VERSION=1.0.0 -v $GITHUB_WORKSPACE/build:/build deb_build
          cp build/swisstronik_1.0.0_amd64.deb swisstronik_1.0.0_amd64.deb
      - uses: actions/upload-artifact@v3
        with:
          name: swisstronik_1.0.0_amd64.deb
          path: swisstronik_1.0.0_amd64.deb